export default [
  { id: 1, name: 'Humanoid' },
  { id: 2, name: 'Lycanthrope' },
  { id: 3, name: 'Undead' },
  { id: 4, name: 'Giant' },
  { id: 5, name: 'Construct' },
  { id: 6, name: 'Extraplanar' },
  { id: 7, name: 'Magical' },
  { id: 12, name: 'Vampyre' },
  { id: 13, name: 'Atenha Ra' },
  { id: 14, name: 'Greater Akheva' },
  { id: 15, name: 'Khati Sha' },
  { id: 19, name: 'Zek' },
  { id: 21, name: 'Animal' },
  { id: 22, name: 'Insect' },
  { id: 23, name: 'Monster' },
  { id: 24, name: 'Elemental' },
  { id: 25, name: 'Plant' },
  { id: 26, name: 'Dragon' },
  { id: 28, name: 'Summoned Creature' },
]
