export default [
  { id: 0, name: 'Agnostic', mask: 1 << 0 },
  { id: 1, name: 'Bertoxxulous', mask: 1 << 1 },
  { id: 2, name: 'Brell Serilis', mask: 1 << 2 },
  { id: 3, name: 'Cazic Thule', mask: 1 << 3 },
  { id: 4, name: 'Erollisi Marr', mask: 1 << 4 },
  { id: 5, name: 'Bristlebane', mask: 1 << 5 },
  { id: 6, name: 'Innoruuk', mask: 1 << 6 },
  { id: 7, name: 'Karana', mask: 1 << 7 },
  { id: 8, name: 'Mithaniel Marr', mask: 1 << 8 },
  { id: 9, name: 'Prexus', mask: 1 << 9 },
  { id: 10, name: 'Quellious', mask: 1 << 10 },
  { id: 11, name: 'Rallos Zek', mask: 1 << 11 },
  { id: 12, name: 'Rodcet Nife', mask: 1 << 12 },
  { id: 13, name: 'Solusek Ro', mask: 1 << 13 },
  { id: 14, name: 'The Tribunal', mask: 1 << 14 },
  { id: 15, name: 'Tunare', mask: 1 << 15 },
  { id: 16, name: 'Veeshan', mask: 1 << 16 },
]
