export default [
  { id: 0, name: 'HELD', mask: 1 << 0 },
  { id: 1, name: 'EAR', mask: 1 << 1 },
  { id: 2, name: 'HEAD', mask: 1 << 2 },
  { id: 3, name: 'FACE', mask: 1 << 3 },
  { id: 4, name: 'EAR', mask: 1 << 4 },
  { id: 5, name: 'NECK', mask: 1 << 5 },
  { id: 6, name: 'SHOULDERS', mask: 1 << 6 },
  { id: 7, name: 'ARMS', mask: 1 << 7 },
  { id: 8, name: 'BACK', mask: 1 << 8 },
  { id: 9, name: 'WRIST', mask: 1 << 9 },
  { id: 10, name: 'WRIST', mask: 1 << 10 },
  { id: 11, name: 'RANGE', mask: 1 << 11 },
  { id: 12, name: 'HANDS', mask: 1 << 12 },
  { id: 13, name: 'PRIMARY', mask: 1 << 13 },
  { id: 14, name: 'SECONDARY', mask: 1 << 14 },
  { id: 15, name: 'FINGERS', mask: 1 << 15 },
  { id: 16, name: 'FINGERS', mask: 1 << 16 },
  { id: 17, name: 'CHEST', mask: 1 << 17 },
  { id: 18, name: 'LEGS', mask: 1 << 18 },
  { id: 19, name: 'FEET', mask: 1 << 19 },
  { id: 20, name: 'WAIST', mask: 1 << 20 },
  { id: 21, name: 'AMMO', mask: 1 << 21 },
]
