export default [
  { id: 0, name: '1H Blunt' },
  { id: 1, name: '1H Slashing' },
  { id: 2, name: '2H Blunt' },
  { id: 3, name: '2H Slashing' },
  { id: 4, name: 'Abjuration' },
  { id: 5, name: 'Alteration' },
  { id: 6, name: 'Apply Poison' },
  { id: 7, name: 'Archery' },
  { id: 8, name: 'Backstab' },
  { id: 9, name: 'Bind Wound' },
  { id: 10, name: 'Bash' },
  { id: 11, name: 'Block' },
  { id: 12, name: 'Brass Instruments' },
  { id: 13, name: 'Channeling' },
  { id: 14, name: 'Conjuration' },
  { id: 15, name: 'Defense' },
  { id: 16, name: 'Disarm' },
  { id: 17, name: 'Disarm Traps' },
  { id: 18, name: 'Divination' },
  { id: 19, name: 'Dodge' },
  { id: 20, name: 'Double Attack' },
  { id: 21, name: 'Dragon Punch' },
  { id: 22, name: 'Dual Wield' },
  { id: 23, name: 'Eagle Strike' },
  { id: 24, name: 'Evocation' },
  { id: 25, name: 'Feign Death' },
  { id: 26, name: 'Flying Kick' },
  { id: 27, name: 'Forage' },
  { id: 28, name: 'Hand to Hand' },
  { id: 29, name: 'Hide' },
  { id: 30, name: 'Kick' },
  { id: 31, name: 'Meditate' },
  { id: 32, name: 'Mend' },
  { id: 33, name: 'Offense' },
  { id: 34, name: 'Parry' },
  { id: 35, name: 'Pick Lock' },
  { id: 36, name: 'Piercing' },
  { id: 37, name: 'Riposte' },
  { id: 38, name: 'Round Kick' },
  { id: 39, name: 'Safe Fall' },
  { id: 40, name: 'Sense Heading' },
  { id: 41, name: 'Singing' },
  { id: 42, name: 'Sneak' },
  { id: 43, name: 'Specialize Abjure' },
  { id: 44, name: 'Specialize Alteration' },
  { id: 45, name: 'Specialize Conjuration' },
  { id: 46, name: 'Specialize Divination' },
  { id: 47, name: 'Specialize Evocation' },
  { id: 48, name: 'Pick Pockets' },
  { id: 49, name: 'Stringed Instruments' },
  { id: 50, name: 'Swimming' },
  { id: 51, name: 'Throwing' },
  { id: 52, name: 'Tiger Claw' },
  { id: 53, name: 'Tracking' },
  { id: 54, name: 'Wind Instruments' },
  { id: 55, name: 'Fishing' },
  { id: 56, name: 'Make Poison' },
  { id: 57, name: 'Tinkering' },
  { id: 58, name: 'Research' },
  { id: 59, name: 'Alchemy' },
  { id: 60, name: 'Baking' },
  { id: 61, name: 'Tailoring' },
  { id: 62, name: 'Sense Traps' },
  { id: 63, name: 'Blacksmithing' },
  { id: 64, name: 'Fletching' },
  { id: 65, name: 'Brewing' },
  { id: 66, name: 'Alcohol Tolerance' },
  { id: 67, name: 'Begging' },
  { id: 68, name: 'Jewelry Making' },
  { id: 69, name: 'Pottery' },
  { id: 70, name: 'Percussion Instruments' },
  { id: 71, name: 'Intimidation' },
  { id: 72, name: 'Berserking' },
  { id: 73, name: 'Taunt' },
]
