name: cd

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Download db
        run: npm run preparedb

      - name: Generate
        run: npm run generate
        env:
          NUXT_APP_BASE_URL: /EqDbWeb/
          NODE_OPTIONS: "--max_old_space_size=16384"

      - name: Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
